insert into character (id, name, movie) values (1, 'Groot', 'Guardians of the Galaxy');
insert into character (id, name, movie) values (2, 'Gamora', 'Guardians of the Galaxy');
insert into character (id, name, movie) values (3, 'Star-Lord', 'Guardians of the Galaxy');
insert into character (id, name, movie) values (4, 'Rocket', 'Guardians of the Galaxy');
insert into character (id, name, movie) values (5, 'Zaphod Beeblebrox', 'Hitchhiker''s Guide to the Galaxy');
insert into character (id, name, movie) values (6, 'Slartibartfast', 'Hitchhiker''s Guide to the Galaxy');
insert into character (id, name, movie) values (7, 'Arthur Dent', 'Hitchhiker''s Guide to the Galaxy');
insert into character (id, name, movie) values (8, 'Ford Prefect', 'Hitchhiker''s Guide to the Galaxy');
insert into character (id, name, movie) values (9, 'Marvin the Paranoid Android', 'Hitchhiker''s Guide to the Galaxy');
insert into character (id, name, movie) values (10, 'Darth Vader', 'Star Wars');
insert into character (id, name, movie) values (11, 'Count Dooku', 'Star Wars');
insert into character (id, name, movie) values (12, 'The Imperator', 'Star Wars');
insert into character (id, name, movie) values (13, 'Luke Skywalker', 'Star Wars');
insert into character (id, name, movie) values (14, 'Han Solo', 'Star Wars');
insert into character (id, name, movie) values (15, 'Princess Leia', 'Star Wars');
insert into character (id, name, movie) values (16, 'Anakin Skywalker', 'Star Wars');
insert into character (id, name, movie) values (17, 'Obi Wan Kenobi', 'Star Wars');