package io.reflectoring.dto;

public enum DesignationConstant {
    CHIEF_EXECUTIVE_OFFICER,
    CHIEF_TECHNICAL_OFFICER,
    VICE_PRESIDENT,
    SENIOR_MANAGER,
    MANAGER,
    ARCHITECT,
    SENIOR_SOFTWARE_ENGINEER,
    SOFTWARE_ENGINEER,
    INTERN,
    OTHERS
}