DROP TABLE IF EXISTS USERS;
  
CREATE TABLE USERS (
  FIRST_NAME VARCHAR(250) NOT NULL,
  LAST_NAME VARCHAR(250) NOT NULL,
  MOBILE VARCHAR(250)  NULL,
  EMAIL VARCHAR(250)  NULL,
  PROFILE_URL VARCHAR(250)  NULL
);