CREATE TABLE IF NOT EXISTS BOOK( ID INTEGER  NOT NULL, NAME VARCHAR(45) NOT NULL, PRIMARY KEY(ID));

CREATE TABLE IF NOT EXISTS PUBLISHER_BOOK( BOOK_ID INTEGER  NOT NULL, PUBLISHER_ID INTEGER NOT NULL, PRIMARY KEY(BOOK_ID, PUBLISHER_ID));

CREATE TABLE IF NOT EXISTS PUBLISHER( ID INTEGER  NOT NULL, NAME VARCHAR(45) NOT NULL, PRIMARY KEY(ID));

CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START WITH 1 INCREMENT BY 1;
